version: '3.8'

services:
  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network

  app: # for worker and API server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - API_KEY=${API_KEY}
      - CX_ID=${CX_ID}
      - CRUX_API_KEY=${CRUX_API_KEY}
    networks:
      - app-network
    volumes:
      - ./static:/app/static

networks:
  app-network:
    driver: bridge
